#!/bin/python3
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import register_runner

if __name__ == "__main__":
	chips, _ = register_runner.get_chips()
	if len(sys.argv) != 2:
		sys.stderr.write("Usage: %s <device>" % sys.argv[0])
		sys.stderr.write("Available devices:")
		for chip in chips:
			sys.stderr.write("  %s" % chip)
		sys.exit(1)

	devices = list(filter(lambda x: x["dev_type"].lower() == sys.argv[1].lower(), chips))

	sys.stderr.write(f"Have {len(chips)} chips, {len(devices)} match of type {sys.argv[1]}")

	if len(devices) == 0:
		sys.stderr.write(f"No devices of type {sys.argv[1]} found")
		sys.exit(1)

	device = random.choice(devices)
	sys.stderr.write(f"Selected {device['serial']}")

	print(device['serial'])

